# Generated by Django 5.1 on 2024-09-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.IntegerField()),
                ('prod_name', models.CharField(max_length=30)),
                ('prod_type', models.CharField(max_length=30)),
                ('prod_image', models.ImageField(default='', upload_to='image')),
            ],
        ),
    ]
